### ISSUE TITLE
[RFC] Criteria for crates to be listed

### ISSUE THREAD

**Issue by orium** [rust-lang/arewewebyet#127]
According to the contribution guidelines old, unmaintained, crates can be added.  Also, crates that are not established can be added (e.g. a crate with 500 download is probably no "web yet").  This also implies that they should not be removed.

I believe there is no value in having unmaintained crates, as well as crates that have very minimal use.  I suggest changing the `CONTRIBUITING.md` to reflect that.

**Comment by LukeMathWalker** [comment]
We started to discuss this today with @adriantombu and it feels reasonable to introduce minimum criteria for crates to be listed on www.arewewebyet.org

Something minimal that I think would be a good baseline:

- The crate's repository is not archived
- The crate is not flagged as unmaintained by `cargo audit`
- The crate has at least X recent downloads

Establishing what a reasonable value for `X` is could be controversial, but we can start with something very low (50? 100?) as a filter for crates that have just been published and are not quite ready to be recommended to people as being "web yet".   

I wouldn't use "last commit" as a filter since some crates can be considered "done" and therefore receive no commit activity even though they are widely used.

Wdyt? @ibraheemdev @Turbo87 @marcoow

**Comment by Turbo87** [comment]
I'd recommend a slightly higher limit due to https://blog.rust-lang.org/2024/03/11/crates-io-download-changes.html, but other than that this sounds reasonable 👍

**Comment by Turbo87** [comment]
another thought: it probably makes sense to limit the number of entries per category to some degree. e.g. if we already have 15 entries for category X then adding a 16th one would need a stronger argument than adding a second one to category Y which only had a single entry so far.

**Comment by LukeMathWalker** [comment]
> another thought: it probably makes sense to limit the number of entries per category to some degree. e.g. if we already have 15 entries for category X then adding a 16th one would need a stronger argument than adding a second one to category Y which only had a single entry so far.

I agree, although I would set a high limit (e.g. 10?).

**Comment by adriantombu** [comment]
Hey folks, just chiming in to see if there is anything more to discuss here to achieve an agreement so that we can start cleaning the issues 💪🏼

**Comment by LukeMathWalker** [comment]
I think we're good to go if we figure out a "minimum number of recent downloads" number. Based on the recent changes to crates.io, I think 2000 is a good initial threshold. We can adjust if needed.

**Comment by adriantombu** [comment]
For reference, I'm around 2k-4k downloads for my published crates that no one uses so I bet we can go even higher 😄

**Comment by LukeMathWalker** [comment]
We can raise it to 4k, but I wouldn't go any further as "the first line".

**Comment by adriantombu** [comment]
To summerize the discussion so far, here are the main criterias:

- The crate's repository is not archived
- The crate is not flagged as unmaintained by cargo audit
- The crate has at least 4k recent downloads
- Limit the number of entries per category to 10

Does it look reasonable for everyone?

I'll have several days off this week and the coming one, so if we can agree on those criterias I can have a first pass on the issues.
