### ISSUE TITLE
Add stpl ("super template") engine

### ISSUE THREAD

**Issue by bee-git** [rust-lang/arewewebyet#154]
https://github.com/dpc/stpl
https://docs.rs/stpl
https://crates.io/crates/stpl

**Comment by ibaryshnikov** [comment]
@bee-git last release was Dec 31, 2017, is it still maintained?

**Comment by ibaryshnikov** [comment]
It doesn't look very active: there's only one issue on gh, last commit was on Jul 2018, and the downloads are low. I'm closing it, but feel free to reopen if the things change.

**Comment by bereddy** [comment]
I guess I misunderstood the purpose of AreWeWebYet. I thought it was a resource to surface, in as comprehensive a way as possible, all the resources someone might want to use if they're using Rust for web-related development. I already can use Google to find the leading, most active projects for web-related work. What saves me time is when a resource exists that I can trust to lead me to just about everything out there for a particular task. If you want, you can divide sections into "active projects" and "less active, or inactive, projects". But just limiting the lists to active, popular projects doesn't make the list very helpful to me (and, I suspect, others). It also can prevent projects from getting attention that might deserve attention, and might become active with a bit more interest.

**Comment by ibaryshnikov** [comment]
@bereddy thanks for writing! I'd like to clarify what `low` means
<img width="808" alt="downloads" src="https://user-images.githubusercontent.com/9951788/68948003-f5af1580-07c7-11ea-8c46-bf45457be769.png">

What do you think about the following paragraph?
https://blog.rust-lang.org/inside-rust/2019/10/03/Keeping-secure-with-cargo-audit-0.9.html#new-feature-unmaintained-crate-warnings

**Comment by bereddy** [comment]
I can see how it might be useful to list things like Github stars, number of downloads, and time since last code update in some sort of brief way next to each crate name in each section of AreWeWebYet. If that information is used to also develop a "unmaintained" flag, that's fine.

All I can say is that when I realized that a popularity filter was being put in place as to what crates would be listed on AreWeWebYet, I stopped using AreWeWebYet, and I stopped making suggestions for additions to the lists on the site.

To me, in an age where Google is so good at surfacing what is popular, the purpose of AreWebWebYet should be its comprehensive nature. This is not only useful to people looking for crates to serve their needs. A comprehensive list also gives people interested in creating new crates a better sense of what already has been tried.

I think, for example, that this templating crate, [DisplayAs](https://github.com/droundy/display-as), is very original and could be useful to many people, and might spark others to develop crates similar to it. It's not popular, however, so after the reaction to the less popular crates suggested here, I decided not to bother suggesting it for AreWeWebYet.

In a similar vein, there was a time when [Ructe](https://github.com/kaj/ructe) was not particularly well known as a templating engine. Some people pointed it out on Reddit, however, and even though it hardly was known, it started to attract some attention.

It's up to you and the other maintainers of AreWeWebYet to decide what filter you want to use for items to be included in your directories. I simply was surprised, and disappointed, when I found out that the goal was NOT to be as comprehensive as possible.
