### ISSUE TITLE
Showlist the features

### ISSUE THREAD

**Issue by JostCrow** [rust-lang/arewewebyet#49]
Maybe it is an idea to showlist the features of the packages. That way you can check if what you need is already there or not.  Just like the comment below

![screenshot from 2016-08-15 11-10-49](https://cloud.githubusercontent.com/assets/390575/17660333/0839130a-62d9-11e6-82e0-f36286435317.png)

**Comment by gnunicorn** [comment]
Thanks for the comment and yes, that'd be neat feature to have, but it is hard to maintain and curate – even in the mid-run. We are trying to keep up to date with what is happening and report as we notice things, but it would be taking too much time if we tried to keep those lists up to date – especially since very few projects keep proper changelogs 😦  . And then, IMHO, it is better to not provide any list than promote false information. Unfortunately we don't have the time to maintain such a list.

Though, I feel our in-between approach of having specific comments by specific people with clear indication which version and what time that comment was made, gives you some good idea. Of course, we'd like to have more. If you have any – even as quotes from blog posts – please add a PR and we gladly merge. I am sure people would appreciate it.

So, I hope you understand why I am closing this as a wontfix,  unless you want to join the team and keep maintaining it. In that case feel free to reopen and let us know about that!

**Comment by Manishearth** [comment]
That said, I personally (not sure about @ligthyear) am okay with project maintainers approaching us and saying that they would like to keep such a list up to date.

**Comment by JostCrow** [comment]
I can understand that it is to time consuming. I do not have the time to do it myself.

But it would be nice indeed if the project maintainers approached this repo to update the list.

**Comment by gnunicorn** [comment]
If any project maintainer would like to do that, I am open to discussing that.  We are also super open to post their news on our blog, too – the blog template is even set up to be a quote from an external source. You really just have to propose it. Haven't been approached by anyone yet though...
