### ISSUE TITLE
Diesel is now on stable

### ISSUE THREAD

**Issue by dwillie** [rust-lang/arewewebyet#70]
https://github.com/diesel-rs/diesel/releases/tag/v0.10.0

This is a fairly big deal as far as how 'web' rust is, I think

edit: I mean like, properly on stable not using the syntex stuff.

**Comment by radix** [comment]
Hi, thanks for the issue!

I'm not sure exactly what this issue is requesting, though. There's no mention on AWWW that diesel is nightly-only.  I realize it's been over a year since you filed this issue, though, so maybe it used to have some wording that has now been changed.

So I'm going to close this ticket for now, but if you think something else should be done, please feel free to comment and I'll re-open it.
